[package]
name = "rust-ratelimit"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.12.0", features = ["full"] }
awaitgroup = "0.6.0"
async-channel = "1.6.1"